services:
  pos-devsoul:
    image: pos-devsoul:$CI_COMMIT_REF_NAME-latest
    container_name: pos-devsoul-$CI_COMMIT_REF_NAME-Website
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
