apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bun-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Umershamshad53/bun-app.git  # Change if needed
    targetRevision: HEAD
    path: bun-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
