apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bun-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - bun-app.786999.xyz
    secretName: bun-app-tls
  rules:
    - host: bun-app.786999.xyz  # Change to your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bun-app
                port:
                  number: 80
